requires 'Dancer2', '0.207000';
requires 'Plack', '1.0047';
requires 'Starman', '0.4014';
requires 'Method::Signatures';
requires 'common::sense';
requires 'namespace::clean';
requires 'Template::Toolkit';
requires 'File::Slurper';
requires 'DBD::SQLite';
requires 'JSON';
requires 'XML::LibXML';
requires 'LWP::Protocol::https';