#!/home/ccsoft/perls/cm/perl -CSD


#see
#https://en.wikipedia.org/wiki/Braille_ASCII

# "Unicode includes a means for encoding eight-dot Braille; however, Braille ASCII continues to be the preferred format for encoding six-dot Braille."


use v5.12;
use utf8;
use JSON;
use LWP::Simple;
use Data::Dumper;
use Getopt::Long;
use lib qw(.);
use H2BEncoder;
use common::sense;

my $printHebrew =0;
my $printBrailleUnicode =0;
my $printBrailleAscii =0;
my $highlightTaamim =0;
my $tEncoding ='CO';
GetOptions("print-hebrew|w" => \$printHebrew,
	   "print-braille-unicode|u" => \$printBrailleUnicode,
	   "print-braille-ascii|a" => \$printBrailleAscii,
	   "highlight-taamim|t" => \$highlightTaamim,
	   "taammim-encoding|e=s" => \$tEncoding,

	   );

my $enc = H2BEncoder->new(mode => $tEncoding);

while(<>){
    chomp;
    emitLine($_);
}

exit 0;
sub emitLine{    
    my $line = shift;

    say $line if $printHebrew;

    my $p1Pure = $enc->heb2BrUni($line);

    
    my $p1 = $enc->heb2BrUni($line, highlightTaamim => $highlightTaamim);
    say $p1 if $printBrailleUnicode;
    
    my $p2 = $enc->brUni2BrAscii($p1Pure);
    say $p2 if $printBrailleAscii;

    
}
